name: FocusFlow
options:
  bundleIdPrefix: com.theportlandcompany
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  FocusFlow:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FocusFlow
    resources:
      - path: FocusFlow/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.theportlandcompany.focusflow
        INFOPLIST_FILE: FocusFlow/Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: VP38993WK6
        CODE_SIGN_ENTITLEMENTS: FocusFlow/Resources/FocusFlow.entitlements
    info:
      path: FocusFlow/Resources/Info.plist
      properties:
        CFBundleDisplayName: Focus Flow
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIUserInterfaceStyle: Dark
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        CFBundleURLTypes:
          - CFBundleURLName: focusflow
            CFBundleURLSchemes:
              - focusflow
